{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{literal}
<!--[if lt IE 8]>
<style>
/* Terminate floating elements flow in IE < 8 */
.float-break
{
  height: 1%;
}
</style>
<![endif]-->
<!--[if IE]>
<style type="text/css">
legend
{
position:relative;
top:-0.7em;
}
fieldset
{
margin-top:1.4em;
padding-top:0;
}
{** admin2pp specific part **}
#preview-dialog fieldset
{
margin-top:10px;
}
</style>
<![endif]-->
{/literal}
