{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $dynamic_csm_disabled = ezini('TreeMenu','Dynamic','contentstructuremenu.ini')|ne('enabled')}

{if $dynamic_csm_disabled}
<style type="text/css">

div#contentstructure ul#content_tree_menu ul li {ldelim} padding-left: 0; {rdelim}
div#contentstructure ul#content_tree_menu ul ul {ldelim} margin-left: 20px; {rdelim}

</style>
{/if}

{literal}
<!--[if lt IE 8]>
<style type="text/css">
.float-break /* Terminate floating elements flow in IE < 8 */
{
    height: 1%;
}
</style>
<![endif]-->
<!--[if IE]>
<style type="text/css">
legend
{
position:relative;
top:-0.7em;
}
fieldset
{
margin-top:1.4em;
padding-top:0;
}
{** admin2pp specific part **}
#preview-dialog fieldset
{
margin-top:10px;
}
</style>
<![endif]-->
{/literal}
